# See https://golangci-lint.run/usage/integrations/ for editor integrations
# Supports VSCode and vim-go
run:
  concurrency: 8
  tests: true
  go: '1.21'

issues:
  new-from-branch: master
  max-same-issues: 0
  max-issues-per-linter: 0
  fix: true
  exclude:
    - dot-imports # Log package imports
    - var-naming
    - blank-imports
    - SA9004 # Assuming types is fine
    - receiver-naming # Covered with another linter
    - exported # Some names need matching with package prefix

    # stylecheck
    - ST1001 # . imports are okay for errors
    - ST1003 # Checking for capitalization. Very messy
    - ST1016 # Receiver consistency. A few packages break this too much

    # gosec
    - G402 # We enable InsecureSkipVerify on purpose sometimes
    - G101 # Checks hardcoded credentials, but fails on API path names
    - G204 # Complains about passing variable arguments to exec commands
    - G602 # Potential slice out of bound, sometimes erroneous

  exclude-rules:
    # Ignore erroneous unused test functions
    # Ignore unused context and unset responses from API interfaces
    # Ignore hardcoded JSON objects
    # Ignore long base64 encoded strings in tests
    - path: nas/api/cluster_test.go
      linters:
        - unused
    - path: pkg/api/service/v1
      linters:
        - unparam
        - lll
    - path: internal/dao/profile.go
      linters:
        - lll
    - path: sys/notify.go
      linters:
        - lll
    - path: sqldb/internal_alerts.go
      linters:
        - lll
    - path: sys/license
      linters:
        - lll

linters-settings:
  cyclop:
    max-complexity: 15

  errcheck:
    check-type-assertions: true
    check-blank: false

  errchkjson:
    report-no-exported: true

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        mapstructure: snake

  gocritic:
    disabled-checks:
      - captLocal
      - commentFormatting
      - ifElseChain
      - sloppyReassign
      - singleCaseSwitch
      - commentedOutCode # Useful to disable
    enabled-tags:
      - experimental
      - opinionated
    rules:
      tooManyResultsChecker:
        maxResults: 3
      nestingReduce:
        bodyWidth: 4
      hugeParam:
        sizeThreshold: 64

  gocyclo:
    min-complexity: 20

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/iXsystems/TrueCommand/middleware)

    custom-order: true

  goconst:
    min-occurrences: 2
    numbers: false # Using gomnd
    ignore-calls: true # Too picky with structured logging
    ignore-tests: true # Don't be so picky with specific test constants
    match-constant: false

  gomnd:
    ignored-numbers:
      - '100.0'
      - '10'
      - '2'
      - '3'

    ignored-files:
      - 'nas/obj/util.go'

  godot:
    period: false
    capital: false

  misspell:
    ignore-words:
      - dynamicdns

  revive:
    rules:
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T"

  govet:
    check-shadowing: true

  testpackage:
    allow-packages:
      - v1 # API service tests rely on a lot of unexported structure parameters

  unparam:
    check-exported: true

  lll:
    line-length: 180
    tab-width: 2


linters:
  enable-all: true
  disable:
    # Whitespace related
    - wsl
    - whitespace
    - nlreturn

    # These are wholely unnecessary
    - wrapcheck # Functions matching error return to be replaced with custom err variable
    - varnamelen
    - exhaustivestruct # Using every struct method when initializing
    - exhaustive # Using every enum constant in switch
    - exhaustruct
    - funlen # Restrict funtions to variable lines
    - nonamedreturns # Naming returns for 2+ returns of the same type is good, but not required
    - errchkjson
    # We don't need these at all
    - gofumpt
    - interfacebloat
    - ireturn
    - depguard
    - tagalign
    # Could be nice, but not fully compatible
    - contextcheck # Doesn't like global contexts or gin interface checks
    - forbidigo # Fmt is useful and accessible in a few instances
    - dupl # Doesn't like boilerplate interfaces
    - tagliatelle # Will need to make sure UI doesn't break, but consistency is good
    - gochecknoglobals # Too picky
    - errcheck # Weird with go routines that can return errors
    - nakedret # Doesn't work with named types
    - forcetypeassert # I'd personally rather force a panic in rare cases like this
    # Parallel tests are too finicky
    - tparallel 
    - paralleltest
    - thelper # Unhelpful about use of testing.TB
    - testpackage
    - testableexamples

    # Priority to fix
    - goerr113 # Ensure all errors are typed
    - godox # Shows TODO comments

    # Complexity linters
    - nestif
    - gocognit
    - gocyclo
    - cyclop
    - maintidx

    # Deprecated
    - scopelint
    - interfacer
    - golint
    - ifshort
    - varcheck
    - structcheck
    - nosnakecase
    - deadcode
    - maligned
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - exhaustivestruct
